# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tRUiSJn0cfhXwTtlBBgyc-uFaSdAfdBl
"""

import nltk
from nltk.tag import hmm

train_data = [[("The","DT"),("dog","NN"),("barks","VB")],[("A","DT"),("cat","NN"),("meows","VB")]]

tagger = hmm.HiddenMarkovModelTrainer().train(train_data)

print(tagger.tag(["A","dog","meows"]))