# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dlNG8LcoVu8CEkuFSZUBQIyMXzvYBClD
"""

import spacy
nlp = spacy.load("en_core_web_sm")
text = "running flies copying easily studies"
documents = nlp(text)
lemma = [token.lemma_ for token in documents]
print(lemma)