# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tRUiSJn0cfhXwTtlBBgyc-uFaSdAfdBl
"""

import spacy
nlp = spacy.load("en_core_web_sm")

sentence =  "NLP is fascinating"
doc = nlp(sentence)

print([(token.text,token.pos_) for token in doc])