# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tRUiSJn0cfhXwTtlBBgyc-uFaSdAfdBl
"""

from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

stemmer = PorterStemmer()

words = ['running', 'flies','easily','studies']
stemm_words = [stemmer.stem(word) for word in words]

print("Stemmed Words:", stemm_words)