# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tRUiSJn0cfhXwTtlBBgyc-uFaSdAfdBl
"""

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

words =["This",'is',"a","simple","example","of","stopword","removel"]
filtered_words = [word for word in words if word.lower() not in stopwords.words('english')]

print("Filtered Words:", filtered_words)