# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dlNG8LcoVu8CEkuFSZUBQIyMXzvYBClD
"""

import nltk
nltk.download("punkt_tab")
nltk.download("punkt")

from nltk.tokenize import word_tokenize, sent_tokenize
text="Natural Language processing is Amazing! It enables machines to understand text."
print("Word tokens:", word_tokenize(text))
print("Sentence tokens:", sent_tokenize(text))

import spacy
nlp = spacy.load("en_core_web_sm")
text ="tokenization is crucial for NLP!"
documents = nlp(text)
tokens = [token.text for token in documents]
print(tokens)